name: docker-stable (skip)
on:
  pull_request:
    paths-ignore:
      - .github/workflows/docker-stable.yml
      - "**/*.go"
      - "chain/**"
      - "cmd/gossamer/**"
      - "dot/**"
      - "internal/**"
      - "lib/**"
      - "pkg/**"
      - scripts/integration-test-all.sh
      - go.mod
      - go.sum

jobs:
  docker-stable-tests:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Skipping workflow. See why this workflow exists:"
          echo "https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks"
